package com.example.tiktokapp.repositories

import com.example.tiktokapp.domain.models.Country

object CountryRepository {
    val countries = listOf(
        Country("Afghanistan", "AF", "+93"),
        Country("Afrique du Sud", "ZA", "+27"),
        Country("Albanie", "AL", "+355"),
        Country("Algérie", "DZ", "+213"),
        Country("Allemagne", "DE", "+49"),
        Country("Andorre", "AD", "+376"),
        Country("Angola", "AO", "+244"),
        Country("Antigua-et-Barbuda", "AG", "+1-268"),
        Country("Arabie Saoudite", "SA", "+966"),
        Country("Argentine", "AR", "+54"),
        Country("Arménie", "AM", "+374"),
        Country("Australie", "AU", "+61"),
        Country("Autriche", "AT", "+43"),
        Country("Azerbaïdjan", "AZ", "+994"),
        Country("Bahamas", "BS", "+1-242"),
        Country("Bahreïn", "BH", "+973"),
        Country("Bangladesh", "BD", "+880"),
        Country("Barbade", "BB", "+1-246"),
        Country("Belgique", "BE", "+32"),
        Country("Belize", "BZ", "+501"),
        Country("Bénin", "BJ", "+229"),
        Country("Bhoutan", "BT", "+975"),
        Country("Biélorussie", "BY", "+375"),
        Country("Birmanie", "MM", "+95"),
        Country("Bolivie", "BO", "+591"),
        Country("Bosnie-Herzégovine", "BA", "+387"),
        Country("Botswana", "BW", "+267"),
        Country("Brésil", "BR", "+55"),
        Country("Brunei", "BN", "+673"),
        Country("Bulgarie", "BG", "+359"),
        Country("Burkina Faso", "BF", "+226"),
        Country("Burundi", "BI", "+257"),
        Country("Cambodge", "KH", "+855"),
        Country("Cameroun", "CM", "+237"),
        Country("Canada", "CA", "+1"),
        Country("Cap-Vert", "CV", "+238"),
        Country("Chili", "CL", "+56"),
        Country("Chine", "CN", "+86"),
        Country("Chypre", "CY", "+357"),
        Country("Colombie", "CO", "+57"),
        Country("Comores", "KM", "+269"),
        Country("Congo-Brazzaville", "CG", "+242"),
        Country("Congo-Kinshasa", "CD", "+243"),
        Country("Corée du Nord", "KP", "+850"),
        Country("Corée du Sud", "KR", "+82"),
        Country("Costa Rica", "CR", "+506"),
        Country("Croatie", "HR", "+385"),
        Country("Cuba", "CU", "+53"),
        Country("Danemark", "DK", "+45"),
        Country("Djibouti", "DJ", "+253"),
        Country("Dominique", "DM", "+1-767"),
        Country("Égypte", "EG", "+20"),
        Country("Émirats arabes unis", "AE", "+971"),
        Country("Équateur", "EC", "+593"),
        Country("Érythrée", "ER", "+291"),
        Country("Espagne", "ES", "+34"),
        Country("Estonie", "EE", "+372"),
        Country("Eswatini", "SZ", "+268"),
        Country("Éthiopie", "ET", "+251"),
        Country("Fidji", "FJ", "+679"),
        Country("Finlande", "FI", "+358"),
        Country("France", "FR", "+33"),
        Country("Gabon", "GA", "+241"),
        Country("Gambie", "GM", "+220"),
        Country("Géorgie", "GE", "+995"),
        Country("Ghana", "GH", "+233"),
        Country("Grèce", "GR", "+30"),
        Country("Grenade", "GD", "+1-473"),
        Country("Guatemala", "GT", "+502"),
        Country("Guinée", "GN", "+224"),
        Country("Guinée-Bissau", "GW", "+245"),
        Country("Guinée équatoriale", "GQ", "+240"),
        Country("Guyana", "GY", "+592"),
        Country("Haïti", "HT", "+509"),
        Country("Honduras", "HN", "+504"),
        Country("Hongrie", "HU", "+36"),
        Country("Îles Cook", "CK", "+682"),
        Country("Îles Marshall", "MH", "+692"),
        Country("Îles Salomon", "SB", "+677"),
        Country("Inde", "IN", "+91"),
        Country("Indonésie", "ID", "+62"),
        Country("Irak", "IQ", "+964"),
        Country("Iran", "IR", "+98"),
        Country("Irlande", "IE", "+353"),
        Country("Islande", "IS", "+354"),
        Country("Israël", "IL", "+972"),
        Country("Italie", "IT", "+39"),
        Country("Jamaïque", "JM", "+1-876"),
        Country("Japon", "JP", "+81"),
        Country("Jordanie", "JO", "+962"),
        Country("Kazakhstan", "KZ", "+7"),
        Country("Kenya", "KE", "+254"),
        Country("Kirghizistan", "KG", "+996"),
        Country("Kiribati", "KI", "+686"),
        Country("Koweït", "KW", "+965"),
        Country("Laos", "LA", "+856"),
        Country("Lesotho", "LS", "+266"),
        Country("Lettonie", "LV", "+371"),
        Country("Liban", "LB", "+961"),
        Country("Libéria", "LR", "+231"),
        Country("Libye", "LY", "+218"),
        Country("Liechtenstein", "LI", "+423"),
        Country("Lituanie", "LT", "+370"),
        Country("Luxembourg", "LU", "+352"),
        Country("Macédoine du Nord", "MK", "+389"),
        Country("Madagascar", "MG", "+261"),
        Country("Malaisie", "MY", "+60"),
        Country("Malawi", "MW", "+265"),
        Country("Maldives", "MV", "+960"),
        Country("Mali", "ML", "+223"),
        Country("Malte", "MT", "+356"),
        Country("Maroc", "MA", "+212"),
        Country("Maurice", "MU", "+230"),
        Country("Mauritanie", "MR", "+222"),
        Country("Mexique", "MX", "+52"),
        Country("Micronésie", "FM", "+691"),
        Country("Moldavie", "MD", "+373"),
        Country("Monaco", "MC", "+377"),
        Country("Mongolie", "MN", "+976"),
        Country("Monténégro", "ME", "+382"),
        Country("Mozambique", "MZ", "+258"),
        Country("Namibie", "NA", "+264"),
        Country("Nauru", "NR", "+674"),
        Country("Népal", "NP", "+977"),
        Country("Nicaragua", "NI", "+505"),
        Country("Niger", "NE", "+227"),
        Country("Nigeria", "NG", "+234"),
        Country("Norvège", "NO", "+47"),
        Country("Nouvelle-Zélande", "NZ", "+64"),
        Country("Oman", "OM", "+968"),
        Country("Ouganda", "UG", "+256"),
        Country("Ouzbékistan", "UZ", "+998"),
        Country("Pakistan", "PK", "+92"),
        Country("Palaos", "PW", "+680"),
        Country("Panama", "PA", "+507"),
        Country("Papouasie-Nouvelle-Guinée", "PG", "+675"),
        Country("Paraguay", "PY", "+595"),
        Country("Pays-Bas", "NL", "+31"),
        Country("Pérou", "PE", "+51"),
        Country("Philippines", "PH", "+63"),
        Country("Pologne", "PL", "+48"),
        Country("Portugal", "PT", "+351"),
        Country("Qatar", "QA", "+974"),
        Country("République centrafricaine", "CF", "+236"),
        Country("République tchèque", "CZ", "+420"),
        Country("République démocratique du Congo", "CD", "+243"),
        Country("Roumanie", "RO", "+40"),
        Country("Royaume-Uni", "GB", "+44"),
        Country("Russie", "RU", "+7"),
        Country("Rwanda", "RW", "+250"),
        Country("Saint-Christophe-et-Niévès", "KN", "+1-869"),
        Country("Saint-Marin", "SM", "+378"),
        Country("Saint-Vincent-et-les-Grenadines", "VC", "+1-784"),
        Country("Sainte-Lucie", "LC", "+1-758"),
        Country("Salvador", "SV", "+503"),
        Country("Samoa", "WS", "+685"),
        Country("São Tomé-et-Principe", "ST", "+239"),
        Country("Sénégal", "SN", "+221"),
        Country("Serbie", "RS", "+381"),
        Country("Seychelles", "SC", "+248"),
        Country("Sierra Leone", "SL", "+232"),
        Country("Singapour", "SG", "+65"),
        Country("Slovaquie", "SK", "+421"),
        Country("Slovénie", "SI", "+386"),
        Country("Somalie", "SO", "+252"),
        Country("Soudan", "SD", "+249"),
        Country("Soudan du Sud", "SS", "+211"),
        Country("Sri Lanka", "LK", "+94"),
        Country("Suède", "SE", "+46"),
        Country("Suisse", "CH", "+41"),
        Country("Suriname", "SR", "+597"),
        Country("Syrie", "SY", "+963"),
        Country("Tadjikistan", "TJ", "+992"),
        Country("Tanzanie", "TZ", "+255"),
        Country("Tchad", "TD", "+235"),
        Country("Thaïlande", "TH", "+66"),
        Country("Timor oriental", "TL", "+670"),
        Country("Togo", "TG", "+228"),
        Country("Tonga", "TO", "+676"),
        Country("Trinité-et-Tobago", "TT", "+1-868"),
        Country("Tunisie", "TN", "+216"),
        Country("Turkménistan", "TM", "+993"),
        Country("Turquie", "TR", "+90"),
        Country("Tuvalu", "TV", "+688"),
        Country("Ukraine", "UA", "+380"),
        Country("Uruguay", "UY", "+598"),
        Country("Vanuatu", "VU", "+678"),
        Country("Vatican", "VA", "+379"),
        Country("Venezuela", "VE", "+58"),
        Country("Viêt Nam", "VN", "+84"),
        Country("Zambie", "ZM", "+260"),
        Country("Zimbabwe", "ZW", "+263")
    )
}